version: 2.1

orbs:
  hub: 'yasuhiroki/hub@0.0.2'

jobs:
  Test-Code-Quality:
    docker:
      - image: cimg/python:3.7.7
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "Pipfile.lock" }}
      - run: pipenv install
      - run: pipenv run pre-commit run --all-files
      - save_cache:
          paths:
            - ~/.cache
          key: dependencies-{{ checksum "Pipfile.lock" }}
#      - persist_to_workspace:
#          root: /home/circleci/
#          paths: project


  Build-And-Push-Image:
    docker:
      - image: cimg/python:3.7.7
    steps:
      - checkout
#      - attach_workspace:
#          at: /home/circleci/
      - setup_remote_docker:
         version: 19.03.13
      - run:
          name: build and push
          command: |
            docker build -t $DOCKER_LOGIN/circleci-demo:latest .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $DOCKER_LOGIN/circleci-demo:latest


  Update-Pre-Commit:
    docker:
      - image: cimg/python:3.7.7
    steps:
      - checkout
      - hub/install
      - add_ssh_keys: &ssh_key
          fingerprints:
            - "e6:3d:fa:c4:44:3b:8b:37:88:94:98:42:c5:50:79:b1"
      - run:
          name: Switch to branch
          command: git checkout -b new_branch

      - run:
          name: install & update pre-commit
          command: |
            pipenv install
            pipenv run pre-commit autoupdate

      - run:
         name: Create pull request if update
         command: |
           git status -s | grep .pre-commit-config.yaml &&
           git add .pre-commit-config.yaml &&
           git config --global user.email pacohm94@gmail.com &&
           git config --global user.name packituz-gttz &&
           git push -u origin new_branch &&
           hub pull-request --no-edit -b master
#           git commit -m "Pre-commit hooks upgrade" &&
#           git push --set-upstream origin new_branch



workflows:
  Build-and-Test:
    jobs:
#      - Test-Code-Quality
#      - Build-And-Push-Image:
#          requires:
#            - Test-Code-Quality
      - Update-Pre-Commit:
          filters:
            branches:
              only:
                - master
#  Monthly-Update:
#    triggers:
#      - schedule:
#          cron: "0 17 * * *"
#          filters:
#            branches:
#              only:
#                - master
#    jobs:
#      - Update-Pre-Commit